#!/bin/bash
SEARCH_STRING="trace_print"
REPLACE_STRING="TRACE_INFO"
if [ "$1" = "" ]; then
  echo "Usage $0 fileName SearchString ReplaceString : Output file filename.temp"
  echo "Defaults: SearchString=$SEARCH_STRING ReplaceString=$REPLACE_STRING"
else
    if [ "$2" != "" ]; then
      SEARCH_STRING=$2
      echo "Search String: $SEARCH_STRING"
    fi
    if [ "$3" != "" ]; then
      REPLACE_STRING=$3
      echo "Replace String: $REPLACE_STRING"
    fi
cat  -n $1 | sed -n "$!N;:start;$!{
    /\n/ !N;
    /{/ !{P;D;N;b start}#We are not inside function ,Just print the line and move to next line
    /)[ ]*[\n]*.*{/ {             # Check for line having { of Function
                     /.*{.*}.*\n.*/ {p;n;b start}  #Print the line if it has both {} brace and move to next Line
                     /.*\n.*{.*}.*/ {p;n;b start}  #Print the line if it has both {} brace and move to next Line
                     x
                     /{/ { s/{/{{/;x;p;b SearchStr} #Opening { found, append it to Function_name stored on HOLD space
                     /{/ !{    #Hold space doesnot have FunctionName
                                z;x;p;
                                :a;{s/\( .*\)\( *(.*\)/\1/ ; ta;} # recursively remove string after function bracket (
                                s/ *$// # Remove if any space at end of line
                                # Get function name , convert to Upper case , Push to Hold buffer , then jump to SearchStr
                                s/.* \(.*\)/\1{/;y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/; h;tSearchStr;
                          }
                          b
                          :SearchStr
                          $!  {
                                :NextLine
                                 n                   # Add Next Line to Pattern space
                                 /$SEARCH_STRING/ !{p;} # Print Line as it is as
                                /{/ {x;s/{/{{/;x;tNextLine;} # Inside Fn , go to NextLine
                                /}/ {x;s/{//;
                                        /{/ {x;b NextLine;} # Inside Fn ,go to NextLine
                                        x;b # if '}' found Exit SearchStr()
                                    }
                                /$SEARCH_STRING/  {    # Replace the string and add Function Name + curent Line as first parameter
                                                        G #Get fn name to PATT
                                                        s/\( *\)\([0-9]*\)\(.*\)$SEARCH_STRING *(\(.*;\)\n*\n\(.*[^{]\).*/\1\2\3$REPLACE_STRING(\5_\2,\4/
                                                        p
                                                  }
                                b NextLine # Go to Next Line
                          }
                    }
}" | sed -rn '{s/^[ ]*[0-9]+\t//p}' > $1.temp # Remove the space Line number \t from file
    # cat $1.temp
     echo ""
     echo "--- Output file : $1.temp"
fi
#}">$1.temp
