#!/bin/bash
SEARCH_STRING="trace_print"
REPLACE_STRING="TRACE_INFO"

if [ "$1" = "" ]; then
  echo "Usage $0 fileName SearchString ReplaceString : Output file filename.temp"
  echo "Defaults: SearchString=$SEARCH_STRING ReplaceString=$REPLACE_STRING"
else
    if [ "$2" != "" ]; then
      SEARCH_STRING=$2
      echo "Search String: $SEARCH_STRING"
    fi
    if [ "$3" != "" ]; then
      REPLACE_STRING=$3
      echo "Replace String: $REPLACE_STRING"
    fi
    cat  -n $1 | sed -n "$!N;
      $!{
            /)[ ]*[\n]*.*{/ !p; #Check for line NOT having { of Function

            /)[ ]*[\n]*.*{/ {   # Check for line having { of Function
              x ; s/.*// ; x        # Clear the Hold buffer
              p;

              :a s/\( .*\)\( *(.*\)/\1/ ; ta; # recursively remove string after function bracket (

              s/ *$//  # Remove if any space at end of line
              # Get function name , convert to Upper case , Push to Hold buffer , then jump to SearchStr
              s/.* \(.*\)/\1/;y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/; H;tSearchStr;
              b # branch to end

              :SearchStr
                $!  {
                    n                   # Add Next Line to Pattern space
                    /$SEARCH_STRING/ !{p;} # Print Line as it is as
                    /{/ tSearchStr      # if '{' found go to NextLine
                    /}/ b               # if '}' found Exit SearchStr()

                    /$SEARCH_STRING/ { # if serach string found
                        H              # Push it to Hold buffer
                        x              # Get function name + current line to Pattern space
                        #Replace the string and add Function Name + curent Line as first parameter
                        s/\n*\(.*\)\n\( *\)\([0-9]*\)\(.*\)$SEARCH_STRING(\(.*;\)\n*/\2\3\4$REPLACE_STRING(\1_\3,\5/p
                        s/.*$REPLACE_STRING(\(.*\)_[0-9]*.*/\1/ #Get function name to Pattern space
                        x            # Push the Function name to Hold buffer
                    }
                    b SearchStr      # Go to Next Line
                }
            }
        }
    " | sed -rn '{s/(^[ ]*[0-9][0-9]*)[ ]*(.*)/\2/ ;s/\t//p}' > $1.temp # Remove the \tLine number from file
     cat $1.temp
     echo "--- Output file : $1.temp"
fi
